# Header
menu:
  Home: /
  Archives: /archives

social:
    github:
    lastfm:
    linkedin:
    instagram:
    twitter:



title: Gautsch Codes
tagline:
    main: Passionate for technology, simplicity,
    highlight: and great code.
