# Header
menu:
  home: /
  archives: /archives

keywords:
    - Developer
    - Development
    - Web Development
    - JavaScript
    - CSS
    - HTML

social:
    github:
        name: dgautsch
        link: https://github.com/dgautsch
    linkedin:
        name: dangautsch
        link: https://www.linkedin.com/in/dangautsch/
    instagram:
        name: dgooches
        link: https://www.instagram.com/dgooches/
    twitter:
        name: gautschcodes
        link: https://twitter.com/gautschcodes



title: Gautsch Codes
tagline:
    main: Passionate for technology, simplicity,
    highlight: and great code.
