# Header
menu:
  Home: /
  Archives: /archives

keywords:
    - Developer
    - Development
    - Web Development
    - JavaScript
    - CSS
    - HTML

social:
    github:
    lastfm:
    linkedin:
    instagram:
    twitter:



title: Gautsch Codes
tagline:
    main: Passionate for technology, simplicity,
    highlight: and great code.
